name: KBFFA
version: 2.0
author: MayusYT
main: net.snapecraft.KnockbackFFA.Main
commands:
    kbffa:
        description: All commands for KBFFA.
        usage: /kbffa <setup[2-4]|lobby|leave>
    build:
        description: Buildmode in the Lobby!
    kit:
        description: Opens a GUI where you can buy or equip kits.
    kits:
        description: Opens a GUI where you can buy or equip kits.
